# This file was generated by GoReleaser. DO NOT EDIT.
class Bump < Formula
  desc "Draft GitHub Release of the next semver in web browser"
  homepage "https://github.com/mroth/bump"
  version "0.2.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/mroth/bump/releases/download/v0.2.2/bump_0.2.2_mac_x64.tar.gz"
    sha256 "947ce6acfe18f2bf5aa94e0028e4fa4bda1151ed9ab031bc342d623b34d00350"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/mroth/bump/releases/download/v0.2.2/bump_0.2.2_linux_x64.tar.gz"
      sha256 "51806eaa9138559713b98974262d49f81456cded840c9c06877efe5c997ae2e4"
    end
  end

  def install
    bin.install "bump"
  end
end
