# This file was generated by GoReleaser. DO NOT EDIT.
class Deepclean < Formula
  desc "Scan and remove junk files from source code directories"
  homepage "https://github.com/mroth/deepclean"
  version "0.2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/mroth/deepclean/releases/download/v0.2.0/deepclean_0.2.0_mac_x64.tar.gz"
    sha256 "ea7ec1cf79c4cdca272e47d29ad824e092117620b70e228a825b0a00c97f3ad7"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/mroth/deepclean/releases/download/v0.2.0/deepclean_0.2.0_linux_x64.tar.gz"
      sha256 "483ce8cb00e5952797356df02e5bf0884837b07bc765061a151ce3657503a0fb"
    end
  end

  def install
    bin.install "deepclean"
  end
end
