# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitSemverDescribe < Formula
  desc "git describe with semantic version 2.0 compatible names"
  homepage "https://github.com/mroth/semverdesc"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/mroth/semverdesc/releases/download/v0.1.1/git-semver-describe_0.1.1_mac_arm64.tar.gz"
      sha256 "e64ec4ecad9d1034b171eea574c7cedcdf8c44033892b320cea5be9eef862ded"

      def install
        bin.install "git-semver-describe"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mroth/semverdesc/releases/download/v0.1.1/git-semver-describe_0.1.1_mac_x64.tar.gz"
      sha256 "f5cfc8a895b724ec047a932997a7455f60b19becf800f15dc36a419900b3f4f0"

      def install
        bin.install "git-semver-describe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mroth/semverdesc/releases/download/v0.1.1/git-semver-describe_0.1.1_linux_arm64.tar.gz"
      sha256 "7126e7a4a5b6832fc3598e876f0ab185448332d705ce905982afcab46cc976e1"

      def install
        bin.install "git-semver-describe"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mroth/semverdesc/releases/download/v0.1.1/git-semver-describe_0.1.1_linux_x64.tar.gz"
      sha256 "d6ddd183bf974a472c25a38dcfb3e4077b301fd2ba5203e8233815f22466568b"

      def install
        bin.install "git-semver-describe"
      end
    end
  end
end
