# This file was generated by GoReleaser. DO NOT EDIT.
class GitSemverDescribe < Formula
  desc "git describe with semantic version 2.0 compatible names"
  homepage "https://github.com/mroth/semverdesc"
  version "0.1.0-rc.2"

  if OS.mac?
    url "https://github.com/mroth/semverdesc/releases/download/v0.1.0-rc.2/git-semver-describe_0.1.0-rc.2_mac_x64.tar.gz"
    sha256 "0510a3089f4987f799279786abb8693044cd19c4abc56252ae548bce899927b9"
  elsif OS.linux?
    url "https://github.com/mroth/semverdesc/releases/download/v0.1.0-rc.2/git-semver-describe_0.1.0-rc.2_linux_x64.tar.gz"
    sha256 "29ccb192a1c9c01a2895c4d5093b5a81358d334ac991205cdd71273407763e6d"
  end

  def install
    bin.install "git-semver-describe"
  end
end
