# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ramdisk < Formula
  desc "Convenience wrapper for creating RAM disks."
  homepage "https://github.com/mroth/ramdisk"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/mroth/ramdisk/releases/download/v0.1.2/ramdisk_0.1.2_macOS_arm64.tar.gz"
      sha256 "a771699cdebbe0f9e84ccc6196172fbc106cd3e6d1b2c58f63b7bf5cb54f18f7"

      def install
        bin.install "ramdisk"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mroth/ramdisk/releases/download/v0.1.2/ramdisk_0.1.2_macOS_x64.tar.gz"
      sha256 "ddf17b1c9f72dbea6333a1a1bd3277f51db9eabea3a9057587b363780de17d28"

      def install
        bin.install "ramdisk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mroth/ramdisk/releases/download/v0.1.2/ramdisk_0.1.2_linux_arm64.tar.gz"
      sha256 "4b1a8d4f0ca59fed107f8b612bc95e0e436dfae935b3760ca1da2cf1730794bf"

      def install
        bin.install "ramdisk"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mroth/ramdisk/releases/download/v0.1.2/ramdisk_0.1.2_linux_x64.tar.gz"
      sha256 "da18418f5f197f751ace82ce12ef4a255b7b124d9c9382ba2313299645634d31"

      def install
        bin.install "ramdisk"
      end
    end
  end
end
