# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scmpuff < Formula
  desc "Adds numbered shortcuts for common git commands."
  homepage "https://mroth.github.io/scmpuff/"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mroth/scmpuff/releases/download/v0.5.0/scmpuff_0.5.0_macOS_x64.tar.gz"
      sha256 "3e8263bb7eeeb6c26ba0e4216c2d3b14c24df17a24a429464a9cec75bb532c00"

      def install
        bin.install "scmpuff"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mroth/scmpuff/releases/download/v0.5.0/scmpuff_0.5.0_macOS_arm64.tar.gz"
      sha256 "01f6587bfc93a48700506621592508096dfc4a19f239c94ae056c89b74daea8e"

      def install
        bin.install "scmpuff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mroth/scmpuff/releases/download/v0.5.0/scmpuff_0.5.0_linux_x64.tar.gz"
      sha256 "3a65755d95ad29c61e5e43012a4466f2aff8ddc3c116f52a02253f2b8ab6da35"

      def install
        bin.install "scmpuff"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mroth/scmpuff/releases/download/v0.5.0/scmpuff_0.5.0_linux_arm64.tar.gz"
      sha256 "dd94dff4b00646b2bf062b61f5c6a00d16d9a71b605c0c4528757767abe4559c"

      def install
        bin.install "scmpuff"
      end
    end
  end

  test do
    ENV["e1"] = "abc"
    assert_equal "abc", shell_output("#{bin}/scmpuff expand 1").strip
  end
end
