# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scmpuff < Formula
  desc "Adds numbered shortcuts for common git commands."
  homepage "https://mroth.github.io/scmpuff/"
  version "0.6.0-rc.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mroth/scmpuff/releases/download/v0.6.0-rc.1/scmpuff_0.6.0-rc.1_darwin_amd64.tar.gz"
      sha256 "33f7449549fa92481aab57786194904d62179a3b04ec6bf74fd005929021001c"

      def install
        bin.install "scmpuff"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mroth/scmpuff/releases/download/v0.6.0-rc.1/scmpuff_0.6.0-rc.1_darwin_arm64.tar.gz"
      sha256 "3fa0c9ed963a0c3c4fa07cdfb9b8e56be9a7737f333636a0b8bf0808a3699a88"

      def install
        bin.install "scmpuff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/mroth/scmpuff/releases/download/v0.6.0-rc.1/scmpuff_0.6.0-rc.1_linux_amd64.tar.gz"
      sha256 "0affebe67ffd1c722579a0a6dabae751658259787eb8be0e9568318ff132b345"
      def install
        bin.install "scmpuff"
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/mroth/scmpuff/releases/download/v0.6.0-rc.1/scmpuff_0.6.0-rc.1_linux_armv6.tar.gz"
      sha256 "3a7193ddcc86b3206df142154a56eb7201787bc49282a5b51b63674282644ab7"
      def install
        bin.install "scmpuff"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/mroth/scmpuff/releases/download/v0.6.0-rc.1/scmpuff_0.6.0-rc.1_linux_arm64.tar.gz"
      sha256 "3a6431a4216a0621d59d943e6cce6172ef027af50632a8356e575e0e8df723fb"
      def install
        bin.install "scmpuff"
      end
    end
  end

  test do
    ENV["e1"] = "abc"
    assert_equal "abc", shell_output("#{bin}/scmpuff expand 1").strip
  end
end
