# This file was generated by GoReleaser. DO NOT EDIT.
class Semverdesc < Formula
  desc "git describe with semantic version 2.0 compatible names"
  homepage "https://github.com/mroth/semverdesc"
  version "0.1.0"

  if OS.mac?
    url "https://github.com/mroth/semverdesc/releases/download/v0.1.0/semverdesc_0.1.0_mac_x64.tar.gz"
    sha256 "d1f7066a251b607ca9fd1f0fbdd62e1d6635dd3e7a7f526419b1d8241bf882ed"
  elsif OS.linux?
    url "https://github.com/mroth/semverdesc/releases/download/v0.1.0/semverdesc_0.1.0_linux_x64.tar.gz"
    sha256 "8016e35e0ad095d674e1be25c4af6e8c3e2f37ff4d6a00767795ae370c3d5541"
  end

  def install
    bin.install "semverdesc"
  end
end
